# Generated by Django 3.2 on 2021-04-07 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_alter_appointment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('speciality', models.CharField(choices=[('NS', 'Neurosurgeon'), ('CD', 'Cardiologist'), ('EN', 'Ear, Nose, & Throat'), ('PD', 'Podiatrist'), ('DT', 'Dentist')], default='DT', max_length=2)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('appointments', models.ManyToManyField(related_name='doctors', to='appointments.Appointment')),
            ],
        ),
    ]
