# Generated by Django 3.2 on 2021-04-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='appointments',
        ),
    ]
