# Generated by Django 3.2 on 2021-04-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctor_appointments'),
        ('appointments', '0002_alter_appointment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctors',
            field=models.ManyToManyField(related_name='doctors', to='doctors.Doctor'),
        ),
    ]
